ALTER TABLE APP_DQHI_DEV.BETTR_TASK
  ADD (
  KEY NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
  , AUDIT_INSERT_DT DATE DEFAULT ON NULL SYSDATE
  )
;;;
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_JOB_NAME ON APP_DQHI_DEV.BETTR_TASK("bettr_task_job_name")
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_NAME ON APP_DQHI_DEV.BETTR_TASK("bettr_task_name")
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_JOB_SORT ON APP_DQHI_DEV.BETTR_TASK("bettr_task_job_sort")
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_SORT ON APP_DQHI_DEV.BETTR_TASK("bettr_task_sort")
;;;CREATE INDEX IDX_BETTR_TASK_OPT_START_DT ON APP_DQHI_DEV.BETTR_TASK("opt_start_dt")
;;;CREATE INDEX IDX_BETTR_TASK_OPT_POLL_REFRESH ON APP_DQHI_DEV.BETTR_TASK("opt_poll_refresh")
CREATE VIEW V_BETTR_TASK (
  KEY
  , BETTR_TASK_JOB_NAME
  , BETTR_TASK_JOB_SORT
  , BETTR_TASK_NAME
  , BETTR_TASK_SORT
  , OPT_START_DT
  , OPT_END_DT
  , OPT_CACHE_EXPIRY_MINS
  , OPT_NUMBER_LIST
  , OPT_CHAR_LIST
  , LAST_TASK_STARTED_DT
  , LAST_HB_DT
  , LAST_STATUS
  , LAST_ERROR
  , LAST_ROWS_AFFECTED
  , AUDIT_INSERT_DT
)

AS (
  SELECT
    KEY BETTR_TASK_KEY
    , "bettr_task_job_name"
    , "bettr_task_job_sort"
    , "bettr_task_name"
    , "bettr_task_sort"
    , "opt_start_dt"
    , "opt_end_dt"
    , "opt_cache_expiry_mins"
    , "opt_number_list"
    , "opt_char_list"
    , "last_task_started_dt"
    , "last_hb_dt"
    , "last_status"
    , "last_error"
    , "last_rows_affected"
    , AUDIT_INSERT_DT
  FROM
    APP_DQHI_DEV.BETTR_TASK
)
