DELETE FROM 
  APP_DQHI_DEV.V_BETTR_TEST_DATA_@@@@
WHERE
  VALUE_NUM = &DELETE_VALUE_NUM
;;;
INSERT INTO APP_DQHI_DEV.V_BETTR_TEST_DATA_@@@@ (
  VALUE_STR
  , VALUE_NUM
)
VALUES (
  &ADD_VALUE_STR
  , &ADD_VALUE_NUM
)