WITH GET_TASKS_WITH_HB_DIFF AS (
  SELECT
    BT.*
    , round (
      extract ( day from SYSDATE - BT.LAST_HB_DT ) * 14400 +
      extract ( hour from SYSDATE - BT.LAST_HB_DT ) * 60  +
      extract ( minute from SYSDATE - BT.LAST_HB_DT )
    ) LAST_HB_MINS
  FROM
    V_BETTR_TASK BT
  WHERE
    BT.BETTR_TASK_GIT_PROJECT = &BETTR_TASK_GIT_PROJECT
    AND BT.BETTR_TASK_GIT_BRANCH = &BETTR_TASK_GIT_BRANCH
)

, GET_FIRST_INCOMPLETE_JOB_TASK AS (
SELECT
  MIN(GTWHD.BETTR_TASK_JOB_ID) BETTR_TASK_JOB_ID
FROM
  GET_TASKS_WITH_HB_DIFF GTWHD
WHERE
  GTWHD.LAST_STATUS IN (
    0 -- Not Started
    , 20 -- Failed
  ) OR (
    GTWHD.LAST_STATUS NOT IN (
      10 -- Started
      , 21 -- Failed, No Retry
    ) AND GTWHD.OPT_CACHE_EXPIRY_MINS > 0
    AND GTWHD.LAST_HB_MINS >= GTWHD.OPT_CACHE_EXPIRY_MINS
  )
)

SELECT
  BT.*
FROM
  GET_TASKS_WITH_HB_DIFF BT
  INNER JOIN GET_FIRST_INCOMPLETE_JOB_TASK GFIJT
    ON BT.BETTR_TASK_JOB_ID = GFIJT.BETTR_TASK_JOB_ID
ORDER BY
  BT.BETTR_TASK_JOB_PRIORITY
  , BT.BETTR_TASK_JOB_ID
  , BT.BETTR_TASK_SORT
