WITH GET_TASKS_AND_EXPIRY_MINS AS (
  SELECT
    BT.*
    , round (
      extract ( day from SYSDATE - BT.LAST_TASK_STARTED_DT ) * 14400 +
      extract ( hour from SYSDATE - BT.LAST_TASK_STARTED_DT ) * 60  +
      extract ( minute from SYSDATE - BT.LAST_TASK_STARTED_DT )
    ) LAST_TASK_STARTED_MINS
  FROM
    V_BETTR_TASK BT
  WHERE
    BT.BETTR_TASK_GIT_PROJECT = &BETTR_TASK_GIT_PROJECT
    AND BT.BETTR_TASK_GIT_BRANCH = &BETTR_TASK_GIT_BRANCH
    AND (
     (
      &INCL_LIVE_REFRESH = 1
      AND BT.OPT_CACHE_EXPIRY_MINS > 0
    ) OR (
      &INCL_HISTORICAL_REFRESH = 1
      AND BT.OPT_CACHE_EXPIRY_MINS <= 0
    )
  )
)

SELECT
  GTAEM.*
FROM
  GET_TASKS_AND_EXPIRY_MINS GTAEM
WHERE
  GTAEM.LAST_STATUS IN (
    0 -- Not Started
    , 20 -- Failed
  ) OR (
    GTAEM.LAST_STATUS NOT IN (
      10 -- Started
      , 21 -- Failed, No Retry
    ) AND GTAEM.OPT_CACHE_EXPIRY_MINS > 0
    AND GTAEM.LAST_TASK_STARTED_MINS >= GTAEM.OPT_CACHE_EXPIRY_MINS
  )
ORDER BY
  GTAEM.BETTR_TASK_JOB_PRIORITY
  , GTAEM.LAST_TASK_STARTED_MINS
  , GTAEM.BETTR_TASK_JOB_ID
  , GTAEM.BETTR_TASK_SORT
