WITH GET_TASKS_WITH_HB_DIFF AS (
  SELECT
    BT.*
    , round (
      extract ( day from SYSDATE - BT.LAST_HB_DT ) * 14400 +
      extract ( hour from SYSDATE - BT.LAST_HB_DT ) * 60  +
      extract ( minute from SYSDATE - BT.LAST_HB_DT )
    ) LAST_HB_MINS
  FROM
    V_BETTR_TASK BT
  WHERE
    BT.BETTR_TASK_GIT_PROJECT = &BETTR_TASK_GIT_PROJECT
    AND BT.BETTR_TASK_GIT_BRANCH = &BETTR_TASK_GIT_BRANCH
    AND (CASE BT.OPT_CACHE_EXPIRY_MINS
      WHEN -1 THEN 0
      ELSE 1
    END) <= &INCL_LIVE_REFRESH
)

SELECT
  GTWHD.*
FROM
  GET_TASKS_WITH_HB_DIFF GTWHD
WHERE
  GTWHD.LAST_STATUS IN (
    0 -- Not Started
    , 20 -- Failed
  ) OR (
    GTWHD.LAST_STATUS NOT IN (
      10 -- Started
      , 21 -- Failed, No Retry
    ) AND GTWHD.OPT_CACHE_EXPIRY_MINS > 0
    AND GTWHD.LAST_HB_MINS >= GTWHD.OPT_CACHE_EXPIRY_MINS
  )
ORDER BY
  GTWHD.BETTR_TASK_JOB_PRIORITY
  , GTWHD.LAST_HB_MINS
  , GTWHD.BETTR_TASK_JOB_ID
  , GTWHD.BETTR_TASK_SORT
