ALTER TABLE APP_DQHI_DEV.BETTR_TASK
  ADD (
  KEY NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
  , AUDIT_INSERT_DT DATE DEFAULT ON NULL SYSDATE
  )
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_JOB_ID ON APP_DQHI_DEV.BETTR_TASK("bettr_task_job_id")
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_GIT_PROJECT ON APP_DQHI_DEV.BETTR_TASK("bettr_task_git_project")
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_GIT_BRANCH ON APP_DQHI_DEV.BETTR_TASK("bettr_task_git_branch")
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_NAME ON APP_DQHI_DEV.BETTR_TASK("bettr_task_name")
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_JOB_PRIORITY ON APP_DQHI_DEV.BETTR_TASK("bettr_task_job_priority")
;;;CREATE INDEX IDX_BETTR_TASK_BETTR_TASK_SORT ON APP_DQHI_DEV.BETTR_TASK("bettr_task_sort")
;;;CREATE INDEX IDX_BETTR_TASK_OPT_START_DT ON APP_DQHI_DEV.BETTR_TASK("opt_start_dt")
;;;CREATE INDEX IDX_BETTR_TASK_OPT_CACHE_EXPIRY_MINS ON APP_DQHI_DEV.BETTR_TASK("opt_cache_expiry_mins")
;;;CREATE VIEW V_BETTR_TASK (
  BETTR_TASK_KEY
  , BETTR_TASK_GIT_PROJECT
  , BETTR_TASK_GIT_BRANCH
  , BETTR_TASK_GIT_COMMIT
  , BETTR_TASK_JOB_COMMENT
  , BETTR_TASK_JOB_ID
  , BETTR_TASK_JOB_PRIORITY
  , BETTR_TASK_NAME
  , BETTR_TASK_SORT
  , OPT_START_DT
  , OPT_END_DT
  , OPT_CACHE_EXPIRY_MINS
  , OPT_NUMBER_LIST
  , OPT_CHAR_LIST
  , LAST_TASK_STARTED_DT
  , LAST_HB_DT
  , LAST_STATUS
  , LAST_ERROR
  , LAST_ROWS_AFFECTED
  , LAST_REPORT
  , AUDIT_INSERT_DT
)

AS (
  SELECT
    KEY
    , "bettr_task_git_project"
    , "bettr_task_git_branch"
    , "bettr_task_git_commit"
    , "bettr_task_job_comment"
    , "bettr_task_job_id"
    , "bettr_task_job_priority"
    , "bettr_task_name"
    , "bettr_task_sort"
    , "opt_start_dt"
    , "opt_end_dt"
    , "opt_cache_expiry_mins"
    , "opt_number_list"
    , "opt_char_list"
    , "last_task_started_dt"
    , "last_hb_dt"
    , "last_status"
    , "last_error"
    , "last_rows_affected"
    , "last_report"
    , AUDIT_INSERT_DT
  FROM
    APP_DQHI_DEV.BETTR_TASK
)
