UPDATE
  V_BETTR_TASK
SET
  LAST_HB_DT = &LAST_HB_DT,
  LAST_STATUS = &LAST_STATUS,
  LAST_TASK_STARTED_DT = &LAST_TASK_STARTED_DT,
  BETTR_TASK_GIT_COMMIT = &BETTR_TASK_GIT_COMMIT,
  LAST_ERROR = &LAST_ERROR
WHERE
  BETTR_TASK_KEY = &BETTR_TASK_KEY